### ISSUE TITLE
Any future?

### ISSUE THREAD

**Issue by dumblob** [flowrigami/flowrigami#2]
Just came across this and wonder whether there is any future development planned or going on as of now.

Could you shed some light on that?

Thanks!

**Comment by flowrigami-sc** [comment]
Hello,

> Just came across this and wonder whether there is any future development planned or going on as of now.
> Could you shed some light on that?
> 
Currently the project development is frozen. No plans for now yet.
If you are interested in the custom development of the component or providing new features for it, let me know please.

Have a good day.

Best regards,
Vadim.

**Comment by dumblob** [comment]
Ah, ok. I wanted to test it as an alternative to https://bpmn.io/ components. But if not backed by any running deployments as of now, I think it's not wise to consider it for new deployments.

Either way, thanks for the answer!
